#!/bin/bash

# =============================================================================
# MOTU M4 JACK System-wide Setting Configuration
# =============================================================================
# Script für systemweite JACK-Konfiguration (erfordert sudo)
# Verwendung: sudo ./motu-m4-jack-setting-system.sh [1|2|3|show|remove|help] [--restart]

# Farben für die Ausgabe
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Pfade
SYSTEM_CONFIG_DIR="/etc/motu-m4"
SYSTEM_CONFIG_FILE="$SYSTEM_CONFIG_DIR/jack-setting.conf"

# Prüfen ob als root ausgeführt
check_root() {
    if [ "$EUID" -ne 0 ]; then
        echo -e "${RED}Fehler:${NC} Dieses Script erfordert root-Rechte."
        echo "Bitte mit sudo ausführen: sudo $0 $@"
        exit 1
    fi
}

# Funktion zur Anzeige der verfügbaren Settings
show_settings() {
    echo -e "${BLUE}Verfügbare systemweite JACK-Settings:${NC}"
    echo -e "${GREEN}Setting 1 (Standard):${NC} Niedrige Latenz"
    echo "  - Sample Rate: 48.000 Hz"
    echo "  - Perioden: 3"
    echo "  - Puffergröße: 256 frames"
    echo "  - Latenz: ~5.3 ms"
    echo ""
    echo -e "${GREEN}Setting 2:${NC} Mittlere Latenz"
    echo "  - Sample Rate: 48.000 Hz"
    echo "  - Perioden: 2"
    echo "  - Puffergröße: 512 frames"
    echo "  - Latenz: ~10.7 ms"
    echo ""
    echo -e "${GREEN}Setting 3:${NC} Ultra-niedrige Latenz"
    echo "  - Sample Rate: 48.000 Hz"
    echo "  - Perioden: 3"
    echo "  - Puffergröße: 128 frames"
    echo "  - Latenz: ~2.7 ms"
    echo ""
    echo -e "${YELLOW}Hinweis:${NC} Systemweite Einstellungen werden von allen Benutzern verwendet,"
    echo "außer wenn sie eigene User-Konfigurationen haben."
}

# Funktion zur Anzeige der aktuellen systemweiten Konfiguration
show_current() {
    echo -e "${BLUE}Systemweite JACK-Konfiguration:${NC}"

    if [ -f "$SYSTEM_CONFIG_FILE" ]; then
        local current_setting=$(grep "^JACK_SETTING=" "$SYSTEM_CONFIG_FILE" | cut -d'=' -f2 | tr -d ' ')

        if [ -n "$current_setting" ]; then
            echo -e "${GREEN}Aktives Setting:${NC} $current_setting"

            if [ "$current_setting" = "2" ]; then
                echo -e "${GREEN}Beschreibung:${NC} Mittlere Latenz (48kHz, 2x512, ~10.7ms)"
            elif [ "$current_setting" = "3" ]; then
                echo -e "${GREEN}Beschreibung:${NC} Ultra-niedrige Latenz (48kHz, 3x128, ~2.7ms)"
            else
                echo -e "${GREEN}Beschreibung:${NC} Niedrige Latenz (48kHz, 3x256, ~5.3ms)"
            fi

            echo -e "${BLUE}Konfigurationsdatei:${NC} $SYSTEM_CONFIG_FILE"
        else
            echo -e "${YELLOW}Konfigurationsdatei vorhanden, aber leer${NC}"
        fi
    else
        echo -e "${YELLOW}Keine systemweite Konfiguration vorhanden${NC}"
        echo "Verwendet Standard-Setting 1 (Niedrige Latenz)"
    fi
}

# Funktion zum Setzen des systemweiten Settings
set_system_setting() {
    local setting=$1
    local restart_flag=$2

    if [ "$setting" != "1" ] && [ "$setting" != "2" ] && [ "$setting" != "3" ]; then
        echo -e "${RED}Fehler:${NC} Ungültiges Setting '$setting'. Verwende 1, 2 oder 3."
        exit 1
    fi

    # Verzeichnis erstellen falls nicht vorhanden
    mkdir -p "$SYSTEM_CONFIG_DIR"

    # Konfigurationsdatei erstellen
    echo "# MOTU M4 JACK System-wide Configuration" > "$SYSTEM_CONFIG_FILE"
    echo "# Generated by motu-m4-jack-setting-system.sh on $(date)" >> "$SYSTEM_CONFIG_FILE"
    echo "# Valid values: 1 (niedrige Latenz), 2 (Mittlere Latenz)" >> "$SYSTEM_CONFIG_FILE"
    echo "JACK_SETTING=$setting" >> "$SYSTEM_CONFIG_FILE"

    # Berechtigungen setzen (lesbar für alle)
    chmod 644 "$SYSTEM_CONFIG_FILE"

    echo -e "${GREEN}Systemweites Setting $setting aktiviert!${NC}"

    if [ "$setting" = "2" ]; then
        echo -e "${YELLOW}Konfiguration:${NC} Mittlere Latenz (48kHz, 2x512, ~10.7ms)"
    elif [ "$setting" = "3" ]; then
        echo -e "${YELLOW}Konfiguration:${NC} Ultra-niedrige Latenz (48kHz, 3x128, ~2.7ms)"
    else
        echo -e "${YELLOW}Konfiguration:${NC} Niedrige Latenz (48kHz, 3x256, ~5.3ms)"
    fi

    echo -e "${BLUE}Gespeichert in:${NC} $SYSTEM_CONFIG_FILE"
    echo ""
    echo -e "${YELLOW}Hinweis:${NC} Diese Konfiguration wird für alle Benutzer verwendet,"
    echo "außer wenn sie eigene User-Konfigurationen haben."

    # Automatisches Restart wenn gewünscht
    if [ "$restart_flag" = "--restart" ]; then
        perform_jack_restart
    fi
}

# Funktion für automatisches JACK-Restart
perform_jack_restart() {
    echo ""
    echo -e "${BLUE}=== Automatisches JACK-Restart ===${NC}"

    # Prüfen ob MOTU M4 verfügbar ist
    if ! aplay -l | grep -q "M4"; then
        echo -e "${YELLOW}Warnung:${NC} MOTU M4 nicht gefunden - Restart übersprungen"
        echo "Bitte M4 anschließen und manuell restarten mit:"
        echo "sudo motu-m4-jack-restart-simple.sh"
        return 1
    fi

    # Prüfen ob JACK läuft
    local jack_running=false
    if runuser -l "$(who | grep "(:" | head -n1 | awk '{print $1}')" -c "jack_control status 2>/dev/null | grep -q started" 2>/dev/null; then
        jack_running=true
    fi

    if [ "$jack_running" = false ]; then
        echo -e "${YELLOW}Info:${NC} JACK läuft nicht - starte nur JACK (kein Restart nötig)"
        # Restart-Script aufrufen (behandelt auch den Fall wenn JACK nicht läuft)
        if [ -f "/usr/local/bin/motu-m4-jack-restart-simple.sh" ]; then
            echo "Führe JACK-Start aus..."
            /usr/local/bin/motu-m4-jack-restart-simple.sh
        else
            echo -e "${RED}Fehler:${NC} motu-m4-jack-restart-simple.sh nicht gefunden in /usr/local/bin/"
            return 1
        fi
    else
        echo -e "${GREEN}Info:${NC} JACK läuft - führe Restart durch um neue Einstellungen zu aktivieren"
        # Restart-Script aufrufen
        if [ -f "/usr/local/bin/motu-m4-jack-restart-simple.sh" ]; then
            echo "Führe JACK-Restart aus..."
            /usr/local/bin/motu-m4-jack-restart-simple.sh
        else
            echo -e "${RED}Fehler:${NC} motu-m4-jack-restart-simple.sh nicht gefunden in /usr/local/bin/"
            return 1
        fi
    fi

    echo -e "${GREEN}JACK-Restart abgeschlossen!${NC}"
    echo ""
}

# Funktion zum Entfernen der systemweiten Konfiguration
remove_system_setting() {
    if [ -f "$SYSTEM_CONFIG_FILE" ]; then
        rm -f "$SYSTEM_CONFIG_FILE"
        echo -e "${GREEN}Systemweite Konfiguration entfernt!${NC}"
        echo "Das System verwendet nun das Standard-Setting 1 (Niedrige Latenz)"

        # Verzeichnis entfernen wenn leer
        if [ -d "$SYSTEM_CONFIG_DIR" ] && [ -z "$(ls -A "$SYSTEM_CONFIG_DIR")" ]; then
            rmdir "$SYSTEM_CONFIG_DIR"
            echo "Leeres Konfigurationsverzeichnis entfernt."
        fi
    else
        echo -e "${YELLOW}Keine systemweite Konfiguration vorhanden${NC}"
    fi
}

# Funktion zur Anzeige der Hilfe
show_help() {
    echo -e "${BLUE}MOTU M4 JACK Systemweite Konfiguration${NC}"
    echo ""
    echo "Verwendung:"
    echo "  sudo $0 [1|2|3|show|current|remove|help] [--restart]"
    echo ""
    echo "Optionen:"
    echo "  1        - Setting 1 systemweit aktivieren (Niedrige Latenz)"
    echo "  2        - Setting 2 systemweit aktivieren (Mittlere Latenz)"
    echo "  3        - Setting 3 systemweit aktivieren (Ultra-niedrige Latenz)"
    echo "  show     - Alle verfügbaren Settings anzeigen"
    echo "  current  - Aktuelle systemweite Konfiguration anzeigen"
    echo "  remove   - Systemweite Konfiguration entfernen"
    echo "  help     - Diese Hilfe anzeigen"
    echo ""
    echo "Zusätzliche Optionen:"
    echo "  --restart - Automatisches JACK-Restart nach dem Setzen (nur mit 1, 2 oder 3)"
    echo ""
    echo "Beispiele:"
    echo "  sudo $0 1              # Niedrige Latenz systemweit aktivieren"
    echo "  sudo $0 2 --restart    # Mittlere Latenz aktivieren und sofort anwenden"
    echo "  sudo $0 3 --restart    # Ultra-niedrige Latenz aktivieren und sofort anwenden"
    echo "  sudo $0 current        # Aktuelle Konfiguration anzeigen"
    echo "  sudo $0 remove         # Systemweite Konfiguration entfernen"
    echo ""
    echo "Konfigurationspriorität:"
    echo "  1. Umgebungsvariable JACK_SETTING"
    echo "  2. ~/.config/motu-m4/jack-setting.conf (User-spezifisch)"
    echo "  3. /etc/motu-m4/jack-setting.conf (systemweit)"
    echo "  4. Standard (Setting 1)"
    echo ""
    echo -e "${YELLOW}Hinweis:${NC} Systemweite Einstellungen werden von allen Benutzern verwendet,"
    echo "außer wenn sie eigene User-Konfigurationen haben."
}

# Hauptlogik
case "$1" in
    "1"|"2"|"3")
        check_root
        set_system_setting "$1" "$2"
        ;;
    "show")
        show_settings
        ;;
    "current")
        show_current
        ;;
    "remove")
        check_root
        remove_system_setting
        ;;
    "help"|"-h"|"--help")
        show_help
        ;;
    "")
        echo -e "${YELLOW}Keine Option angegeben.${NC}"
        echo ""
        show_current
        echo ""
        show_settings
        echo "Verwende 'sudo $0 help' für weitere Informationen."
        ;;
    *)
        echo -e "${RED}Fehler:${NC} Unbekannte Option '$1'"
        echo "Verwende 'sudo $0 help' für weitere Informationen."
        exit 1
        ;;
esac
